name: course-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests
  - pip
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - pandas-datareader
  - matplotlib
  - nltk
  - numba
  - pillow
  - scikit-image
  - pip:
      - protobuf
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - seaborn==0.11.1
      - wordcloud==1.8.1