name: course-recommender
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - requests
  - pip
  - mlflow
  - hydra-core
  - jupyter
  - jupyterlab
  - pytorch
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - pandas-datareader
  - matplotlib
  - opencv
  - seaborn
  - cython
  - nltk
  - numba
  - pillow
  - scikit-image
  - tqdm
  - pip:
      - protobuf
      - hydra-joblib-launcher
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - spacy