name: course-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests
  - pip
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - pandas
  - pandas-datareader
  - matplotlib
  - numba
  - pillow
  - scikit-image
  - pip:
      - protobuf
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - scikit-learn==1.0.2
      - seaborn==0.11.1
      - wordcloud==1.8.1
      - nltk==3.6.7
      - gensim==4.1.2
      - scikit-surprise==1.1.1
      - tensorflow==2.7.0
