# conda env create -f conda.yaml tensorflow
# conda activate course-recommender
# conda remove --name course-recommender --all
name: course-recommender
channels:
  - conda-forge
  - defaults
  #- apple
dependencies:
  #- python=3.8
  - tensorflow
  - requests
  - pip
  - jupyter
  - jupyterlab
  - scipy
  - pandas-datareader
  - matplotlib
  - numba
  - pillow
  - scikit-image
  #- tensorflow-deps
  - pip:
      - protobuf
      - wandb
      - autopep8
      - joblib
      - pytest
      - setuptools
      - wheel
      - numpy #==1.23.5
      - pandas #==1.5.3
      - streamlit==1.17.0
      - streamlit-aggrid==0.2.2-2
      - scikit-learn #==1.2.1
      - seaborn #==0.11.1
      - wordcloud==1.8.1
      - nltk==3.6.7
      - gensim==4.1.2
      - scikit-surprise==1.1.1
      #- tensorflow==2.7.0
      #- tensorflow-macos
      #- tensorflow-metal
      #- tensorflow_datasets
